Repository gudtldn/GTL_W08_T8, pull requests merged in 2025-04, with the labels that each got.

#1 Add: Lua, sol2 라이브러리 추가
  .gitignore
  EngineSIU/EngineSIU.vcxproj
  EngineSIU/EngineSIU.vcxproj.filters
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/Lua/bin/Debug/lua.dll
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/Lua/bin/Debug/lua.pdb
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/Lua/bin/Release/lua.dll
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/Lua/bin/Release/lua.pdb
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/Lua/include/lauxlib.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/Lua/include/lua.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/Lua/include/lua.hpp
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/Lua/include/luaconf.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/Lua/include/lualib.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/Lua/lib/Debug/lua.lib
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/Lua/lib/Release/lua.lib
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/sol2/include/sol2/config.hpp
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/sol2/include/sol2/forward.hpp
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/sol2/include/sol2/sol.hpp
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/sol2/sol2.natvis
Labels: size/XXL

#2 Refactor/query_class_list
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/Class.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/ObjectMacros.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/UObjectHash.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/UObjectHash.h
Labels: size/M

#3 Add LuaActor functionality and Lua binding enhancements
  EngineSIU/EngineSIU.vcxproj
  EngineSIU/EngineSIU.vcxproj.filters
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaActor.cpp
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaActor.h
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaManager.cpp
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaManager.h
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaTemplate/LuaActorTemplate.lua
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaTypes/LuaUserTypes.cpp
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaTypes/LuaUserTypes.h
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaUtils/LuaBindMacros.h
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaUtils/LuaBindUtils.h
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/ControlEditorPanel.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/PropertyEditorPanel.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/UnrealEd/SceneManager.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Delegates/Delegate.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Vector.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Vector.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/ObjectTypes.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/StaticMeshComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/EditorEngine.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/Engine.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/Engine.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/EngineTypes.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/GameFramework/Actor.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/GameFramework/Actor.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/UserInterface/Console.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/sol2/include/sol/config.hpp
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/sol2/include/sol/forward.hpp
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/sol2/include/sol/sol.hpp
  EngineSIU/GameJam/Lua/test.lua
Labels: size/XXL

#4 Feature/lua UI
  EngineSIU/EngineSIU.vcxproj
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaManager.cpp
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaManager.h
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaStubs/ALuaActor.lua
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaStubs/FColor.lua
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaStubs/FLinearColor.lua
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaStubs/FMatrix.lua
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaStubs/FQuat.lua
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaStubs/FRotator.lua
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaStubs/FVector.lua
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaStubs/FVector2D.lua
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaStubs/SIUEngine.lua
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaTypes/LuaUserTypes.cpp
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaUtils/LuaBindImGui.cpp
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaUtils/LuaBindImGui.h
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaUtils/LuaStub.h
  EngineSIU/EngineSIU/Engine/Source/Editor/LevelEditor/SLevelEditor.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/ControlEditorPanel.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/PropertyEditorPanel.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/PropertyEditorPanel.h
  EngineSIU/EngineSIU/Engine/Source/Editor/UnrealEd/PrimitiveDrawBatch.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/UnrealEd/PrimitiveDrawBatch.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Delegates/Delegate.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Matrix.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Matrix.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Quat.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Quat.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Vector.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Actors/FireballActor.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Actors/FireballActor.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Collision/BoxComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Collision/BoxComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Collision/CapsuleComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Collision/CapsuleComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Collision/SphereComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Collision/SphereComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/PrimitiveComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/PrimitiveComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/RigidbodyComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/RigidbodyComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/ShapeComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/ShapeComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/StaticMeshComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/StaticMeshComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Launch/Define.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Launch/EngineLoop.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/CollisionRenderPass.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/CollisionRenderPass.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Renderer.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Renderer.h
  EngineSIU/EngineSIU/Shaders/ShaderCollision.hlsl
  EngineSIU/GameJam/Lua/LuaImGui.lua
Labels: size/XXL

#5 Feature/sound manager
  EngineSIU/EngineSIU.vcxproj
  EngineSIU/EngineSIU.vcxproj.filters
  EngineSIU/EngineSIU/Contents/Sound/background.mp3
  EngineSIU/EngineSIU/Engine/Source/Developer/FMOD/SoundManager.cpp
  EngineSIU/EngineSIU/Engine/Source/Developer/FMOD/SoundManager.h
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaManager.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/PropertyEditorPanel.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/PropertyEditorPanel.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Container/String.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Delegates/Delegate.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/FCollision.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/FCollision.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Vector.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/ActorComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Collision/BoxComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Collision/BoxComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Collision/CapsuleComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Collision/CapsuleComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Collision/SphereComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Collision/SphereComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/PrimitiveComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/PrimitiveComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/ShapeComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/ShapeComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Subsystem/CollisionSubsystem.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Subsystem/CollisionSubsystem.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Launch/Define.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Launch/EngineLoop.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Launch/EngineLoop.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Launch/ImGuiManager.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/CollisionRenderPass.cpp
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/fmod/inc/fmod.cs
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/fmod/inc/fmod.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/fmod/inc/fmod.hpp
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/fmod/inc/fmod_codec.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/fmod/inc/fmod_common.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/fmod/inc/fmod_dsp.cs
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/fmod/inc/fmod_dsp.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/fmod/inc/fmod_dsp_effects.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/fmod/inc/fmod_errors.cs
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/fmod/inc/fmod_errors.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/fmod/inc/fmod_output.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/fmod/lib/x64/fmod.dll
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/fmod/lib/x64/fmodL.dll
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/fmod/lib/x64/fmodL_vc.lib
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/fmod/lib/x64/fmod_vc.lib
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/fmod/lib/x86/fmod.dll
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/fmod/lib/x86/fmodL.dll
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/fmod/lib/x86/fmodL_vc.lib
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/fmod/lib/x86/fmod_vc.lib
  EngineSIU/EngineSIU/Font/Roboto-Regular.ttf
  EngineSIU/EngineSIU/Shaders/ShaderCollision.hlsl
Labels: size/XXL

#6 Feature/lua collision
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaActor.cpp
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaActor.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Delegates/Delegate.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Shadow/DirectionalShadowMap.cpp
  EngineSIU/GameJam/Lua/test.lua
Labels: size/M

#7 Refactor and improve safe binding and validation logic
  EngineSIU/EngineSIU.vcxproj
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaActor.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/LevelEditor/SLevelEditor.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Delegates/Delegate.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/ObjectUtils.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/ObjectUtils.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/SafeObjectPtr.h
Labels: size/L

#8 fix: gitignore에 가려졌던 workspace 설정 추가
  EngineSIU.code-workspace
Labels: size/S

#11 Feature/letter box
  EngineSIU/EngineSIU.vcxproj
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/ObjectMacros.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Actors/Player.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Actors/Player.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Camera/CameraComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Camera/CameraComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Camera/CameraModifier.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Camera/CameraModifier.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Camera/PlayerCameraManager.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Camera/PlayerCameraManager.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/GameFramework/Controller.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/GameFramework/Controller.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/GameFramework/Pawn.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/GameFramework/Pawn.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/GameFramework/PlayerController.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/GameFramework/PlayerController.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/UnrealClient.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/CompositingPass.cpp
  EngineSIU/EngineSIU/editor.ini
  EngineSIU/EngineSIU/imgui.ini
Labels: size/L

#12 Feature/camera shake
  EngineSIU/EngineSIU.sln.DotSettings
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaPlayer.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/ControlEditorPanel.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/ObjectTypes.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Camera/CameraModifier.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Camera/CameraModifier.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Camera/CameraModifier_CameraShake.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Camera/CameraModifier_CameraShake.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Camera/CameraShake.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Camera/CameraShake.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Camera/PlayerCameraManager.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Camera/PlayerCameraManager.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Launch/EngineLoop.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Launch/EngineLoop.h
Labels: size/L

#14 Feature/spring arm
  EngineSIU/EngineSIU.vcxproj
  EngineSIU/EngineSIU.vcxproj.filters
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaManager.cpp
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaPlayer.cpp
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaUtils/LuaBindCameraEffect.cpp
  EngineSIU/EngineSIU/Engine/Source/Developer/Lua/LuaUtils/LuaBindCameraEffect.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Actors/Player.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Camera/PlayerCameraManager.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Camera/PlayerCameraManager.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/BillboardComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/BillboardComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Light/LightComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Light/LightComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/PrimitiveComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/PrimitiveComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/SceneComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/SceneComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/SpringArmComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/SpringArmComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/StaticMeshComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/StaticMeshComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/TextComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/TextComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/UTextUUID.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/UTextUUID.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/EditorEngine.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/InteractiveToolsFramework/BaseGizmos/GizmoBaseComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/InteractiveToolsFramework/BaseGizmos/GizmoBaseComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Launch/Define.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/FadeRenderPass.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/FadeRenderPass.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Renderer.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Renderer.h
  EngineSIU/EngineSIU/Shaders/FadeEffect.hlsl
  EngineSIU/GameJam/Lua/Player.lua
Labels: size/XL

#13 Feature/camera_system
  EngineSIU/EngineSIU.vcxproj
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/HAL/PlatformType.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Color.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/MathFwd.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/MathSSE.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/MathUtility.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/MathUtility.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Matrix.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Quat.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Quat.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Vector.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Vector.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Vector4.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Misc/CoreMiscDefines.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/Template/SubclassOf.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/Object.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Camera/PlayerCameraManager.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Camera/PlayerCameraManager.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Collision/CapsuleComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Collision/CapsuleComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/EditorEngine.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/GameFramework/Controller.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/GameFramework/Controller.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/GameFramework/GameModeBase.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/GameFramework/GameModeBase.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/GameFramework/Pawn.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/GameFramework/Pawn.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/GameFramework/PlayerController.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/GameFramework/PlayerController.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/GameFramework/PlayerStart.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/GameFramework/PlayerStart.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/World/World.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/World/World.h
  EngineSIU/EngineSIU/editor.ini
  EngineSIU/EngineSIU/imgui.ini
Labels: size/XXL
